#include "platform/ios/api/api.h"

// This host exports no .gdip plugins. These are the empty-list hook bodies
// generated by Godot's Apple exporter, whose template is in
// editor/export/editor_export_platform_apple_embedded.cpp:1612 at
// ed1daf0bf001b61586d9930840f2f1394092c079. They are required by register_ios_api.
// PartyDeckBridge is an actual compiled engine module and registers through
// initialize_partydeck_ios_probe_module, independently of export plugins.
void godot_apple_embedded_plugins_initialize() {
}

void godot_apple_embedded_plugins_deinitialize() {
}
